### PR TITLE
make it work for normal pypi / Python-3 users (using cgohlke wheel)

### PR DESCRIPTION
**Pull request by stonebig**
would solve https://github.com/ContinuumIO/intake/issues/107,  I suppose

### CODE REVIEW

**Comment by martindurant** [comment]
Thank you, @stonebig 
So I understand, this is to get around a difference in naming convention between conda and pypi's version of ruamel? Does this completely fix #107 , or was some of the issue still outstanding?

**Comment by stonebig** [comment]
it resolves the package naming convention, but:
-  then I fell on the conda prefix https://github.com/ContinuumIO/intake/issues/107#issuecomment-396059722 , workarounded per another try/expect.
- then I failed to find any uc-crime (can you beleive that ?) 
 https://github.com/ContinuumIO/intake/issues/107#issuecomment-396060088 

At that point, I gave up. I suppose Intake is not for pip.

**Comment by seibert** [comment]
This is something we can fix.  Thanks for raising the issue and we can build upon this PR.

**Comment by philippjfr** [comment]
>then I failed to find any us-crime (can you believe that ?)

😄It should be available from the intake channel.

**Comment by martindurant** [comment]
> It should be available from the intake channel.

we do not have a distribution for this in a pure pypi package. I'm afraid that we have been perhaps too opinionated in preferring conda as the distribution engine.

**Comment by seibert** [comment]
Well, pip and PyPI are for Python packages, not for arbitrary package-able artifacts.  There isn't really a natural way to map "data packages" to pip any more than C++ libraries, so I think our opinion in this case is somewhat justified.  :)

However, for ease of running examples, we can rely more on the ability to load catalog and data files over HTTP to remove the need for conda installing things.

**Comment by chobeat** [comment]
any news on this issue?

**Comment by chobeat** [comment]
Is this version already on Pypi?

**Comment by martindurant** [comment]
> Is this version already on PyPI?

It is, but out of date https://pypi.org/project/intake
I'll push a new release. @seibert , can you give me permissions?

**Comment by martindurant** [comment]
-EDIT-
updated on PyPI. Note that that I don't think any of the plugins have been released, and some of them have rather complicated dependencies, so please request releases on the plugins that matter to you.

**Comment by chobeat** [comment]
So far I'm just working with CSV. I will let you know when I will start working with other formats. Thank you

**Comment by martindurant** [comment]
@chobeat , ok cool. Please let me know if install and functionality is OK for you now.
(can close this and #107 , if so)

**Comment by seibert** [comment]
the easier and most useful plugins to do would be:
- intake-parquet
- intake-sql
- intake-xarray

**Comment by chobeat** [comment]
Ok, it worked and now the documentation finally matches the behavior I see on my machine. I had to update a call to `open_csv` but the import works flawlessly

**Comment by martindurant** [comment]
Excellent, thank.

**Pull request closed without merging**
