### PR TITLE
Updating travis to run coveralls

### PR DESCRIPTION
**Pull request by jsignell**
This PR should add a coveralls hook

### CODE REVIEW

**Comment by martindurant** [comment]
Did this work? I can see that the runs passed, but I don't know what I should expect from coveralls to know that stats were successfully transferred.

**Comment by jsignell** [comment]
I wasn't quite sure. The build shows up on coveralls, but I think it needs to get coverage on master to set a baseline.

**Comment by martindurant** [comment]
So we should merge to see what happens?

**Comment by jsignell** [comment]
:)

**Pull request merged**
