### PR TITLE
Add flatten option to server (default True)

### LINKED ISSUE #202: Add a 'flatten' argument to the server CLI
A good suggestion lifted from [this review comment](https://github.com/ContinuumIO/intake/pull/200#discussion_r237260506).

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #202

### CODE REVIEW

**Comment by danielballan** [comment]
Out of curiosity, why flatten by default (or at all)?

**Comment by martindurant** [comment]
Not sure, I didn't write the default, would be happy to change it.

**Comment by danielballan** [comment]
In my case, flattening would create many name collisions, so `False` seems a safer default from my perspective, but I'll be content as long as there is a switch available.

**Comment by martindurant** [comment]
Note that flattening only refers to passing multiple files (or glob) to the intake-server command - is that your situation, @danielballan ?

**Comment by danielballan** [comment]
Oh I see. No. Carry on, sorry for the noise.

**Pull request merged**
