### PR TITLE
Always use `conda info` to find prefix instead of environment

### LINKED ISSUE #48: Conda environment detection with CONDA_PREFIX is unreliable
We added a workaround to discover the conda environment when `$CONDA_PREFIX` is unavailable in:

https://github.com/ContinuumIO/intake/commit/73be37e2f86ffcc5f9a91cd4e81658c8550d1427

However, we've seen a few cases where the `$CONDA_PREFIX` has been set incorrectly, so we should probably only use the approach in the above commit.

### PR DESCRIPTION
**Pull request by martindurant**
Fixes #48

### CODE REVIEW

**Comment by martindurant** [comment]
Still prefers virtualenv's environment variable, if it's set.

**Comment by martindurant** [comment]
(test fail, because they rely on setting CONDA_PREFIX in the in-process environment explicitly)

**Comment by philippjfr** [comment]
Can confirm this change works for me consistently.

**Comment by martindurant** [comment]
OK!

**Pull request merged**
