### PR TITLE
Allow catalog to watch missing directories

### LINKED ISSUE #24: Enable catalog to watch a directory that does not exist
There are situations where a catalog will need to watch a directory that does not exist yet (such as the global environment or user directory).  A few changes to the DirectoryState class should make this possible.

### PR DESCRIPTION
**Pull request by jbcrail**
Fix #24

### CODE REVIEW

**Comment by martindurant** [comment]
Good to see this coming. Would this be affected by #61?

**Comment by martindurant** [comment]
OK good. Would appreciate your thoughts on that PR too, as we strengthen the API.

**Comment by martindurant** [comment]
Sorry, needs merge from master.

**Comment by martindurant** [comment]
(I assume this should no longer be WIP?)

**Comment by jbcrail** [comment]
Yes, this is complete pending a review.

**Comment by jbcrail** [comment]
Sounds good. We'll also have to replace `os.listdir`.

**Comment by jbcrail** [comment]
Regarding bandwidth used by timestamp checks, I had thought about using the `E-Tag` or `If-Modified-Since` headers on the remote Intake server to reduce this traffic. We could use the same technique for S3 or similar URLs.

**Comment by martindurant** [comment]
I don't think that would work, because it would be backend-specific, and still require a call to the storage service, or possibly several, each time the check is done. Basically, I imagine the check-interval being a per-catalogue configuration, which also allows not checking at all.

Something like

```
sources:
  ...
catalogs:
  - mycat:
    - destription: stored on s3
    - url: s3://bucket/cat.yaml
    - refresh: 0
```
for sub-cats, or

```
plugins:
  - ...
sources:
  - ...
config:
  - refresh: 120s
```

**Comment by jbcrail** [comment]
Your proposed interval configuration looks good.

**Comment by martindurant** [comment]
Perhaps that can go into a new issue for tracking.

I am starting to feel like there are enough disperate issues/topics in play simultaneously that we may need to formally move to a project board view.

**Pull request merged**
