### PR TITLE
Adding a favicon

### PR DESCRIPTION
**Pull request by jsignell**
I made this for the status dashboard and thought it should go into the intake repo.

### CODE REVIEW

**Comment by martindurant** [comment]
OK! Does this show up automatically?

**Comment by jsignell** [comment]
I don't think Read The Docs supports project specific favicons. I just wanted to put this somewhere where we can keep track of it in case intake grows and gets a website or something.

**Comment by jsignell** [comment]
See https://continuumio.github.io/intake-dashboard/status.html for instance

**Comment by martindurant** [comment]
You can merge these things at will

**Pull request merged**
