### PR TITLE
Give UserParameter an eval-able repr.

### PR DESCRIPTION
**Pull request by danielballan**
This was useful to me during debugging and may be useful to others.

### CODE REVIEW

**Comment by martindurant** [comment]
Totally in favour, but could use a test

**Comment by martindurant** [comment]
On second thoughts, do you think there's any merit to having this more verbose form only for `str`, so the user has to explicitly print in order to see it?

**Comment by danielballan** [comment]
Fine by me. Changed to `__str__`; added test.

**Comment by martindurant** [comment]
Thanks!

**Pull request merged**
