### PR TITLE
Refactored to make containers a first class citizen.

### PR DESCRIPTION
**Pull request by mmccarty**

### CODE REVIEW

**Comment by martindurant** [comment]
This is extracted from #57 ?

**Comment by mmccarty** [comment]
Yes, I'll update that branch and open a new WIP PR once this one is merged.

**Comment by mmccarty** [comment]
Any further comments here?

**Comment by martindurant** [comment]
I like this PR! I think it's useful, and looks about right, although I haven't spent much time looking at it at all.

My only reservation is around our other conversation - we may end up changing a lot of this in the near future. However, I still think it's a useful step.

**Comment by seibert** [comment]
Looks good, thanks!

**Pull request merged**
